fix(lsp): don't trigger completion on empty lines
This was causing problems in some versions of ipykernel, e.g. 7.3.0.
Hitting Enter at the end of a line like `if True:` would cause an
error like the following to appear in the python console:

Traceback (most recent call last):
File "/Users/JACOB.SCOTT1/Repos/jet/.jet-dev/venv/lib/python3.
11/site-packages/IPython/core/completer.py", line 3678, in _complete
result = matcher(context)
	 ^^^^^^^^^^^^^^^^
File "/Users/JACOB.SCOTT1/Repos/jet/.jet-dev/venv/lib/python3.11/site-packages/IPython/core/completer.py", line 2214, in file_matcher
  code_until_cursor =
  self._extract_code(context.text_until_cursor)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/JACOB.SCOTT1/Repos/jet/.jet-dev/venv/lib/python3.
  11/site-packages/IPython/core/completer.py", line 2316, in _extract_code
      maybe_magic, *rest = line.split(maxsplit=1)
      ^^^^^^^^^^^^^^^^^^
  ValueError: not enough values to unpack (expected at least 1, got 0)

These kinds of completions don't return anything useful anyway, so
dropping them is probably a win all-round.